### ISSUE TITLE
Cannot activate from CTS, must run exe as admin

### ISSUE THREAD

**Issue by Rangoon12** [ScottyMac52/MFDisplay#46]
Config file can only be edited when Notepad++ is run as admin. MFD4CTS will not use my custom settings unless it is run as admin. CTS will not launch MFD4CTS. I am no longer able to access the original dialog window where you input the CTS filepath. I only see the small window with exit or about as options, and the aircraft dropdown. My PC has one account, which is an admin account. I have tried uninstalling and reinstalling. I have tried installing for "all users" and for "just me" with no change in behavior.

**Comment by ScottyMac52** [comment]
It is true that you must be an Admin to edit the config. This is because Windows protects anything in Program Files and below. There is no way to circumvent this that I currently am aware of.

It SHOULD run fine without requiring admin permissions though. I would be very interested in meeting on Discord and trying to walk through it. When are you usually on?

**Comment by ScottyMac52** [comment]
There is a new release coming out today, 2.3.

**Comment by Rangoon12** [comment]
Thanks, and sorry for my slow reply. I have had a busy week but would be happy to connect on Discord at some point maybe middle of this week if it might help out troubleshooting.




I'll reply again probably Monday. 




Best, 


Jeff




On Sat, Feb 9, 2019 at 6:17 PM -0600, "Scott McIntosh" <notifications@github.com> wrote:












There is a new release coming out today, 2.3.

**Comment by Rangoon12** [comment]
We had a snowstorm here, so yesterday got away from me with all the shoveling. I'm available today if that is helpful to meet on Discord. Otherwise I will download the new version and see how that goes.




On Sat, Feb 9, 2019 at 10:37 PM -0600, <jeffmklatt@yahoo.com> wrote:










Thanks, and sorry for my slow reply. I have had a busy week but would be happy to connect on Discord at some point maybe middle of this week if it might help out troubleshooting.




I'll reply again probably Monday. 




Best, 


Jeff




On Sat, Feb 9, 2019 at 6:17 PM -0600, "Scott McIntosh" <notifications@github.com> wrote:












There is a new release coming out today, 2.3.

**Comment by Rangoon12** [comment]
I have the latest MFDisplay and CTS versions as of today, Feb 14th. MFDisplay now launches from CTS. However, it does not launch with my custom settings. Once launched, MFDisplay shows Ka-50 as profile, but does not open any windows. Upon closing, it states the jpeg folder is wrong and asks if I would like to correct that. I say no, then launch MFDisplay (as admin, from my shortcut), and everything works correctly. I get my default profile of UH-1 and my 4 images open to correct positions from my default configuration settings. I have tried running MFDisplay manually without admin priv, but no luck. I must run as admin for it to use my custom config.

**Comment by ScottyMac52** [comment]
What groups does your logged in user belong to on your Windows box? Which version of windows are we talking about as well?

Yeah, I have had bad weather, work issues and personal issues all use up my time so I am being timely with responses either. I really want to get this working so be assured I will not give up!

**Comment by Rangoon12** [comment]
OS Name	Microsoft Windows 10 Pro
Version	10.0.17763 Build 17763

My local users and groups tool says I belong to:
Administrators
Home Users

Thanks for your help with this!

**Comment by ScottyMac52** [comment]
Please try the latest https://github.com/ScottyMac52/MFDisplay/releases/latest release and let me know that works?

**Comment by Rangoon12** [comment]
I installed the latest version, 2.4.1.0   - CTS attempts to launch it, but I get an error stating that the jpeg directory is not valid. It lists a default directory, and says to edit the config file. I double checked my config file. The file is still dated per my last edit on March 3rd, so it doesn't seem to have been overwritten by the new install. It appears that MFD4CTS via CTS is trying to run some other config settings, not my custom settings in the config file.

The only difference in the jpeg path is that I have mine nested within a CTS folder, so that the path is: C:\Users\Jeff\Documents\TARGET Profiles\CTS\Docs\Profile JPGs. It recommends editing the config file. I confirmed that my config file does point to this directory (in fact I just copied and pasted the above path from that file here). 

When I launch MFD4CTS from my own shortcut or the exe directly, everything still works fine. It is using my custom settings from the config and no problems with how it runs. If I run via CTS, I get that error and MFD4CTS does not finish launching.

**Comment by ScottyMac52** [comment]
Thanks for providing that detail. I can work with Don, the CTS author, and see if we can resolve this. I guess the workaround is to:

1.  Start MFD4CTS manually
2.  Then run the CTS configuration 
3.  Hopefully changing modules doesn't break at this point?
