### ISSUE TITLE
Incorrect displays for selected entries

### ISSUE THREAD

**Issue by HomeFries94** [ScottyMac52/MFDisplay#52]
Using the default mfdsettings.config (changing only the target folder) in 2.4, selecting the following aircraft displays the following mfds:

Selected Acft|Displayed MFDs
--------------|------------------
A10C HiViz|LMFD A-4HV
A-4|M2000C (WH) HV
AV-8B|F-14 (left RIO, right Pilot)
AWACS HiViz|No display
C101 HiViz|Fw190
CA|LMFD M2000C WH HV
CA Hiviz|LMFD A-4HV
F-18	|M-200C (HC)
F-18 HiViz|AJS-37
F183 HiViz|no LMFD
F14P HV|RMFD Fw190
F14R HV|LMFD Ka50 HV
F14P|LMFD AJs37, RMFD blank
F-15|Ka-50
F-15HV|LMFD L-39C, RMFD SA342 HV
F-5|LMFD Mi8 HV
F-86HV|RMFD Bf109
Fw190|LMFD P-51
Ka-50 HV|RMFD P-51
L-39C|RMFD SA342
Mi8|RMFD A10C HV
MiG15|LMFD AJS37, RMFD F18 HV
MiG21 HV|LMFD F86 HV, RMFD BF109
P-51|AWACS
SA342|LMFD L-39
Su-25/FC3 HV|C-101
UH-1 HV	|M2000C WH HV

OS: Windows 7 Pro

**Comment by ScottyMac52** [comment]
Did you uninstall the original version as I suggested? It looks like you may be using an older config file.

**Comment by HomeFries94** [comment]
I didn't uninstall, but removed my old mfdsettings.config and ran a repair install to replace it with the default.  I'll try a full uninstall.

**Comment by HomeFries94** [comment]
Ok, I just realized that I did more than just change the folder.  I also inserted my previous LMFD/RMFD dimensions.  The format is identical to the new file, but that's whats making things go nuts.  Using your default numbers makes it work, but my numbers (which shouldn't be much different) cause the other overlays to show up.

Here are my numbers:
`    <add name="LMFD" opacity="1" width="870" height="700" left="2575"
      top="700" xOffsetStart="101" xOffsetFinish="776" yOffsetStart="250"
      yOffsetFinish="900" />
    <add name="RMFD" opacity="1" width="870" height="700" left="4250"
      top="700" xOffsetStart="903" xOffsetFinish="1576" yOffsetStart="250"
      yOffsetFinish="900" />`

**Comment by HomeFries94** [comment]
Leaving your offset numbers intact and just changing my size and monitor displacement numbers to match my setup causes the issues again. 

Here are my test numbers:
`    <add name="LMFD" opacity="1" width="800" height="800" left="3968"
      top="400" xOffsetStart="101" xOffsetFinish="776" yOffsetStart="250"
      yOffsetFinish="900" />
    <add name="RMFD" opacity="1" width="800" height="800" left="4768"
      top="400" xOffsetStart="903" xOffsetFinish="1576" yOffsetStart="250"
      yOffsetFinish="900" />`

**Comment by ScottyMac52** [comment]
Release 2.4.1 will fix this.
