### ISSUE TITLE
Feature Request: Dynamic CAP Drum for F-14 RIO cockpit

### ISSUE THREAD

**Issue by HomeFries94** [ScottyMac52/MFDisplay#56]
Per our discussions, I have enclosed the drum graphic to go with the proposed RIO MFD insert.  Application of the categorized drums should match the following coordinates (note: these are approximate, though the width is always 210px):

Category | Start X | End X
------------ | ------------- | -------------
Bit | 50 | 260
Spl | 325 | 535
Nav | 590 | 800
Tac Data | 860 | 1070
D/L | 1125 | 1335
Tgt Data | 1380 | 1590	

MFD Pixels | <dummy>
------------ | -------------
Start X | 325
End X | 535
Start Y | 350
End Y | 795

Edit: Recommend onscreen placement coordinates be based mathematically on the LMFD screen position so that it adjusts accordingly whenever the LMFD position is updated.

![DCS F14RIO MFD](https://user-images.githubusercontent.com/6812091/57795825-ee258b80-7714-11e9-9ff8-63d5f911791e.jpg)
![F14 CAP Drum](https://user-images.githubusercontent.com/6812091/57795787-d4844400-7714-11e9-8145-93762c493d90.jpg)

**Comment by ScottyMac52** [comment]
Okay, awesome. I have some free time this week and this weekend so I will
get started on this. We will likely have to implement this using a
sub-module type of command and then the barrel selection will send the
module and sub-module command.

When I come up with the command syntax I will document it and then maybe
you can create a TMC test fixture for me to use?

It looks really good, I am looking forward to putting this in 2.6.

Thanks,

Scott

**Comment by ScottyMac52** [comment]
Hey, When are you releasing 2.34? I need the graphic file. ;-)

**Comment by HomeFries94** [comment]
You should be able to open these graphics and right-click to save.  I have plenty left to do before releasing 2.34 (and 2.33 has only been out for a week).  I also sent you the graphics on Discord.

**Comment by ScottyMac52** [comment]
Version 2.6.0 is ready to go that implements this request and fixes a few bugs.

**Comment by HomeFries94** [comment]
A recommendation for insert coordinates: the X/Y offsets for the inserts should be based on the coordinates of the original MFD JPEG rather than the screen display offsets.  All overlays will be tied to the original JPEGs, so tying the insert coordinates to the original JPEG means that no adjustment is necessary when tweaking MFD screen placement.
