### ISSUE TITLE
PNGs in cache not carrying transparency/alpha channel

### ISSUE THREAD

**Issue by HomeFries94** [ScottyMac52/MFDisplay#59]
For submodule overlays that use PNGs to take advantage of the transparency capability of that image type, any transparency is converted to a white channel in the cache file.  This results in the following:
![Screenshot 2019-05-31 08 40 57](https://user-images.githubusercontent.com/6812091/58706428-084fa280-8380-11e9-8833-442ce28fcbd8.png)
instead of what should be
![Screenshot 2019-05-31 08 43 12](https://user-images.githubusercontent.com/6812091/58706500-451b9980-8380-11e9-8cb2-d50aeca48113.png)

**Comment by HomeFries94** [comment]
FYI if abandoning the alpha channel, there's less need for the cache now.  I can also do the overlays in JPG instead of PNG.  However, without transparency, I need to be able to line up overlays pixel to pixel, so this makes tying "startX" to xOffsetStart, "endY" to "yOffsetFinish" that much more critical.

**Comment by ScottyMac52** [comment]
The next version of the utility renamed to MFDMF will support transparent bitmaps. Additionally the sub 
 configuration images will be superimposed on top of the configuration images and saved as cached images.
