### ISSUE TITLE
CTD with F-14 Drum inserts

### ISSUE THREAD

**Issue by HomeFries94** [ScottyMac52/MFDisplay#61]
When selecting one of the drum inserts from either TARGET or command line, I get a CTD.  MFD4CTS was uninstalled/reinstalled, tested with both "Everyone" and "User Only" installation options, and used the default 2.6.2 mfdsettings.config with only edit for JPG path.  Cache was flushed.

With the following command line entry
`mfd4cts -mod F-14R -submod tgt`

the CTD gives the following data:
`Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	MFD4CTS.exe
  Problem Signature 02:	2.6.2.0
  Problem Signature 03:	c39229dd
  Problem Signature 04:	PresentationFramework
  Problem Signature 05:	4.7.3429.0
  Problem Signature 06:	5cdb7ec3
  Problem Signature 07:	d9e
  Problem Signature 08:	17
  Problem Signature 09:	System.InvalidOperationException
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
`

**Comment by ScottyMac52** [comment]
I cannot duplicate the issue. I even ran it from code scoured the debug logs and didn't see any issues the -mod and -submod commands to change the drum. It literally works perfect for me and in my Windows 7 test VM. Can you try it on another machine? Sorry but I have exhausted investigation on my end and the problem signature doesn't really tell me anything useful as far as where in the code it's happening. Sorry!

**Comment by HomeFries94** [comment]
No prob.  I'll see what I can do.

**Comment by HomeFries94** [comment]
I figured it out.

If you call a submod with an invalid (missing) file, you get a CTD.

Example:
mfdsettings.config for F-14 RIO starts as
`    <add moduleName="F-14R" displayName="F-14 Tomcat (RIO)" filename="F-14\DCS F14RIO MFD.jpg">
      <Configurations>
        <add name="LMFD">
          <SubConfigurations>
            <add name="BIT" opacity="1" filename="F-14\F14 CAP Drum.jpg" startX="325" startY="350" endX="535" endY="795" xOffsetStart="50" xOffsetFinish="260" yOffsetStart="1" yOffsetFinish="448" />`
Command
`mfd4cts -mod "F-14R" -submod "BIT"`
causes CTD because the file doesn't exist.  File is now "~MFDisplay_Overlays\F14R LMFD_CAP.jpg".  Replacing the existing filename with this fixes the CTD.

Recommend an error trap that negates the -submod argument if the file is not found.

**Comment by ScottyMacDev** [comment]
Thanks for the steps to reproduce and I have successfully generated the Exception. It is related to trying to show the window when the image is not valid. I will apply a fix and get a 2.6.4 release out.

**Comment by ScottyMac52** [comment]
Release 2.6.4 is out https://github.com/ScottyMac52/MFDisplay/releases/tag/2.6.4. I will leave the issue open until I get a GO. ;-)

**Comment by HomeFries94** [comment]
2.6.5 tests SAT in that no CTD occurs, but ideal implementation would be the MFD insert without the overlay.  That said, not a big deal if filenames are correct.

Speaking of which, please update the F-14 filenames as such:
"~MFDisplay_Overlays\F14R LMFD_CAP.jpg"
~MFDisplay_Overlays\F14R LMFD_CAP_HiVis.jpg"

**Comment by ScottyMac52** [comment]
Updated, there is still an issue with BIT in that it is not the high viz version that is loaded!

**Comment by ScottyMac52** [comment]
I am closing this issue
