### ISSUE TITLE
Feature Request: Multiple MFD preset configurations

### ISSUE THREAD

**Issue by HomeFries94** [ScottyMac52/MFDisplay#63]
Certain MFD users may have different display requirements for different modules.  For example, someone flying the A-10C or F/A-18 may wish to put the in-game display exports to their Cougar MFD screens, while the same person may wish to have MFDisplay show the inserts within the Cougar MFD for the UH-1 or P-51.  Allowing multiple baseline configurations (e.g. "MFD Insert Auxiliary Monitor" and "MFD Insert Superimposed" for the previous examples), and then within the A-10 or UH-1 select 
``preset = "MFD Insert Auxiliary Monitor"``

This would essentially be like having multiple default configurations and choosing which preset (no presets maps to actual default like we have now).

**Comment by ScottyMac52** [comment]
The next version of the utility will have a displays.json file that defines the users display areas. That way all coordinates for configurations will be relative to this display configurations and sub configurations will be relative to the configurations.
