### ISSUE TITLE
"Fw-190" entry must be broken out into "Fw-190A8" and "Fw-190D9"

### ISSUE THREAD

**Issue by HomeFries94** [ScottyMac52/MFDisplay#69]
With separate profiles for both the A8 and D9 variants of the Fw-190, MFDisplay must also create separate profiles for each Fw-190 variant. The current profile is "Fw-190", whereas CTS calls "Fw-190A8" and "Fw-190D9".

Recommended entries in mfdsettings.config:
`  

\<add moduleName="Fw-190A8" displayName="Fw-190 A-8 Anton" filename="Fw-190\DCS Fw190A8 MFD.jpg">

      <Configurations>
		<add name="WHKEY" filename="Fw-190\DCS Fw190A8 WH.jpg" />
      </Configurations>
    </add>
    <add moduleName="Fw-190A8HV" displayName="Fw-190 A-8 Anton HiViz" filename="Fw-190\DCS Fw190A8 MFD HiVis.jpg">
      <Configurations>
		<add name="WHKEY" filename="Fw-190\DCS Fw190A8 WH.jpg" />
      </Configurations>
    </add>
    <add moduleName="Fw-190D9" displayName="Fw-190 D-9 Dora" filename="Fw-190\DCS Fw190D9 MFD.jpg">
      <Configurations>
		<add name="WHKEY" filename="Fw-190\DCS Fw190D9 WH.jpg" />
      </Configurations>
    </add>
    <add moduleName="Fw-190D9HV" displayName="Fw-190 D-9 Dora HiViz" filename="Fw-190\DCS Fw190D9 MFD HiVis.jpg">
      <Configurations>
		<add name="WHKEY" filename="Fw-190\DCS Fw190D9 WH.jpg" />
      </Configurations>
    </add>`

**Comment by ScottyMacDev** [comment]
I updated the shipped configuration and it will be deployed with version 2.7 of the product which is currently in work.

**Comment by ScottyMac52** [comment]
This version will not be updated with these configurations.
