### ISSUE TITLE
New required aircraft

### ISSUE THREAD

**Issue by HomeFries94** [ScottyMac52/MFDisplay#70]
The following modules now have profiles in CTS and require corresponding MFDisplay profiles:
F-16C, FW190-A8, I-16, Mig-19,  MB-339

To match CTS, the following profile names are preferred:
```
F-16C
F-16CHV

I-16
I-16HV

Mig-19
Mig-19HV

MB339
MB339HV
```

FYI, the I-16 doesn't currently have MFDs, and the Fw190A8 was addressed in a different issue.

**Comment by HomeFries94** [comment]
Time to add the JF-17 as well:

	<add moduleName="JF-17" displayName="JF-17 Thunder" filename="JF-17\DCS JF17 MFD.jpg">
      <Configurations>
		<add name="WHKEY" filename="JF-17\DCS JF17 WH.jpg" />
       </Configurations>	   
    </add>	
	<add moduleName="JF-17HV" displayName="JF-17 Thunder HiViz" filename="_High Contrast MFDs\DCS JF17 MFD HiVis.jpg">
      <Configurations>
		<add name="WHKEY" filename="JF-17\DCS JF17 WH.jpg" />
       </Configurations>	   
    </add>

**Comment by HomeFries94** [comment]
Another entry for the P-47:

```<add moduleName="P-47D" displayName="P-47D Thunderbolt" filename="P-47D\DCS P47D MFD.jpg">
      <Configurations>
		<add name="WHKEY" filename="P-47D\DCS P47D WH.jpg" />
      </Configurations>
    </add>
    <add moduleName="P-47DHV" displayName="P-47D Thunderbolt HiViz" filename="_High Contrast MFDs\DCS P47D MFD HiVis.jpg">
      <Configurations>
		<add name="WHKEY" filename="P-47D\DCS P47D WH.jpg" />
      </Configurations>
    </add>	  
```
And now the P-51 has a high vis MFD
```
    <add moduleName="P_TF-51DHV" displayName="P-51D Mustang HiViz" filename="_High Contrast MFDs\DCS P51D MFD HiVis.jpg">
      <Configurations>
		<add name="WHKEY" filename="P_TF-51D\DCS P51D WH.jpg" />
      </Configurations>
    </add>
```

**Comment by HomeFries94** [comment]
GitHub isn't letting me edit my post, but the first line should be
```

   <add moduleName="P-47D" displayName="P-47D Thunderbolt" filename="P-47D\DCS P47D MFD.jpg">

```

**Comment by ScottyMac52** [comment]
Can you send me the Mig-19 and I-16 configs you have? I have bought and updated the P-47 Thunderbolt. Now if I can find the time to FLY!

**Comment by HomeFries94** [comment]
MiG-19
```
    <add moduleName="Mig-19" displayName="MiG-19P" filename="Mig-19\DCS Mig19 MFD.jpg">
      <Configurations>
		<add name="WHKEY" filename="Mig-19\DCS Mig19 WH.jpg"  />
      </Configurations>
    </add>
    <add moduleName="Mig-19HV" displayName="MiG-19P HiViz" filename="_High Contrast MFDs\DCS Mig19 MFD HiVis.jpg">
      <Configurations>
		<add name="WHKEY" filename="Mig-19\DCS Mig19 WH.jpg"  />
      </Configurations>
    </add>
```
I-16 (currently there's no MFD, so the filename is a placeholder - joystick only)
```
	<add moduleName="I-16" displayName="I-16 Ishak" filename="I-16\DCS I16 MFD.jpg">
      <Configurations>
		<add name="WHKEY" filename="I-16\DCS I16 WH.jpg" />
		<add name="LMFD" enable="false" />
		<add name="RMFD" enable="false" />
       </Configurations>	   
    </add>
